export const POLITICAS_LEGALES = {
  'politica-datos': {
    titulo: 'Política de Tratamiento de Datos Personales',
    actualizado: '30 de septiembre de 2026',
    introduccion: 'Esta política explica cómo ParteMaquinas trata los datos personales de visitantes, clientes, prospectos y proveedores, y cómo pueden ejercer sus derechos en Colombia.',
    secciones: [
      { titulo: '1. Responsable del tratamiento', parrafos: ['Responsable comercial identificado en este sitio como ParteMaquinas, con domicilio de atención en Carrera 65 #28-27, barrio Trinidad, Medellín, Antioquia, Colombia; teléfono y WhatsApp +57 316 329 3151. Razón social, nombre legal completo y NIT: información pendiente de completar por el titular de la tienda antes de publicación definitiva.', 'Canal de atención de consultas y reclamos: WhatsApp +57 316 329 3151 o comunicación física a la dirección indicada. Al usar WhatsApp, el titular también queda sujeto a las condiciones de ese proveedor.'] },
      { titulo: '2. Datos y finalidades', parrafos: ['Podemos tratar nombre, teléfono, identificadores de contacto, empresa, ciudad, dirección de entrega, datos de cotización y pedido, referencias consultadas, comunicaciones, comprobantes e información técnica del dispositivo y navegación. Solicitamos solo la información pertinente para cada caso.', 'Usamos estos datos para responder consultas; validar referencias y compatibilidades; preparar cotizaciones; gestionar pedidos, pagos, despachos, garantías, devoluciones y servicio posventa; atender peticiones y deberes legales; proteger la seguridad del sitio; administrar el catálogo; y, con autorización cuando corresponda, enviar comunicaciones comerciales.', 'El sitio no solicita datos sensibles ni datos de menores como parte de su operación ordinaria. No envíes esa información por canales de consulta. Si excepcionalmente fuese necesaria, se solicitará autorización explícita y se informará que responder es facultativo.'] },
      { titulo: '3. Autorización, destinatarios y transmisión', parrafos: ['Cuando la ley exige autorización, esta se solicitará antes o al momento de recolectar los datos, indicando su finalidad. La persona puede negarse a autorizar usos no necesarios para atender su consulta o pedido.', 'Para prestar el servicio podemos usar proveedores tecnológicos que procesan datos por cuenta nuestra, entre ellos Vercel (alojamiento y analítica cuando se autoriza), Google y jsDelivr (bibliotecas y decodificador para mostrar modelos 3D; Google Maps cuando se solicita), Tidio (chat cuando se autoriza), WhatsApp y proveedores de transporte o pagos cuando una operación lo requiera. Algunos pueden tratar información desde otros países conforme a sus propios términos y a las garantías aplicables. No vendemos bases de datos personales.'] },
      { titulo: '4. Derechos de los titulares', parrafos: ['Puedes conocer, actualizar y rectificar tus datos; solicitar prueba de la autorización; preguntar por los usos realizados; presentar quejas ante la Superintendencia de Industria y Comercio después de agotar la consulta o reclamo ante el responsable; revocar la autorización o pedir la supresión cuando proceda; y acceder gratuitamente a tus datos.', 'Para consultas o reclamos, escribe al WhatsApp +57 316 329 3151 o envía una comunicación a la dirección física indicada, con el asunto “Protección de datos”, tu nombre, medio para responder, descripción de la solicitud y datos que permitan ubicar la relación. Podemos pedir información razonable para verificar identidad. Las consultas se responden dentro de diez (10) días hábiles desde su recibo; si no es posible, se informa el motivo y la fecha de respuesta, que no podrá superar cinco (5) días hábiles adicionales. Los reclamos se responden dentro de quince (15) días hábiles desde el día siguiente al recibo; si no es posible, se informa el motivo y la fecha, que no podrá superar ocho (8) días hábiles adicionales. Si el reclamo está incompleto, se solicitará completar la información dentro del término legal.'] },
      { titulo: '5. Conservación y seguridad', parrafos: ['Conservaremos los datos durante el tiempo necesario para responder la consulta y cumplir las finalidades descritas, las obligaciones legales, contables, fiscales, de garantía y la defensa de reclamaciones. Después se suprimirán, anonimizarán o conservarán con acceso restringido cuando exista deber legal.', 'Aplicamos controles razonables de acceso, seguridad y confidencialidad. Ninguna transmisión o almacenamiento electrónico puede garantizarse como absolutamente infalible.'] },
      { titulo: '6. Vigencia y cambios', parrafos: ['Esta política rige desde la fecha de actualización indicada. Los cambios sustanciales se publicarán en este sitio antes de aplicar nuevas finalidades, y se solicitará una nueva autorización si la ley lo exige.'] },
    ],
  },
  'terminos-y-condiciones': {
    titulo: 'Términos y Condiciones',
    actualizado: '30 de septiembre de 2026',
    introduccion: 'Estos términos regulan la navegación y las consultas del catálogo de ParteMaquinas. En su versión actual, el sitio muestra productos y permite pedir cotizaciones por WhatsApp; no tiene carrito ni pago integrado.',
    secciones: [
      { titulo: '1. Identificación y contacto', parrafos: ['El sitio es operado bajo el nombre comercial ParteMaquinas desde Carrera 65 #28-27, barrio Trinidad, Medellín, Antioquia, Colombia. Atención: WhatsApp +57 316 329 3151. Razón social o nombre legal completo y NIT: datos pendientes de completar por el titular antes de la publicación definitiva de estos términos.'] },
      { titulo: '2. Uso del catálogo y cotizaciones', parrafos: ['Las fichas, fotografías, descripciones, referencias y modelos 3D sirven como orientación comercial. Puede haber diferencias de presentación, actualización, estado, marca, compatibilidad o disponibilidad. Confirma la aplicación y la referencia con un asesor antes de comprometer una compra.', 'Las fichas que indiquen “precio por confirmar” no son una oferta con precio final. El precio, impuestos, disponibilidad, estado (original, alternativo o remanufacturado), costos y plazo de despacho se informarán de forma clara en la cotización antes de aceptar el pedido. La cotización indicará su vigencia. No se confirma pedido ni se solicita pago por este sitio.', 'El contrato de compraventa se perfecciona cuando comprador y vendedor acuerdan el producto, precio y demás condiciones por un canal escrito. Se enviará o confirmará un resumen del pedido y los datos de pago y entrega antes de recibir el pago. Se emitirán los documentos comerciales y tributarios exigibles.'] },
      { titulo: '3. Pagos, entrega y garantía', parrafos: ['Los métodos de pago, transportadora, costo y plazo de entrega se indicarán en la cotización aceptada. Si no es posible atender el pedido o se presenta una novedad que afecte las condiciones acordadas, se informará al cliente y se aplicarán las soluciones previstas por la ley y por el acuerdo específico.', 'La garantía legal y cualquier garantía adicional se rigen por la Ley 1480 de 2011 y por las condiciones informadas para el producto. Nada en estos términos limita derechos irrenunciables del consumidor. Para solicitar garantía, reporta la referencia, fecha de compra y descripción de la falla por WhatsApp o en la dirección de contacto.'] },
      { titulo: '4. Retracto y reversión del pago', parrafos: ['Cuando la operación sea una venta a distancia y la ley otorgue el derecho de retracto, el consumidor puede ejercerlo dentro de los cinco (5) días hábiles contados desde la entrega del bien, sujeto a las excepciones legales. El procedimiento está en la Política de Derecho de Retracto.', 'La reversión del pago procede únicamente en los casos y bajo el procedimiento del artículo 51 de la Ley 1480 de 2011 y su reglamentación. Consulta el procedimiento con el asesor tan pronto identifiques una causal.'] },
      { titulo: '5. Propiedad intelectual y marcas', parrafos: ['El contenido propio del sitio no puede copiarse o explotarse sin autorización, salvo los usos permitidos por la ley. Los nombres y marcas de fabricantes pertenecen a sus titulares y se usan para identificar productos o compatibilidades; salvo indicación expresa, ParteMaquinas no afirma afiliación con dichos fabricantes. Los modelos 3D son ilustrativos y no sustituyen manuales ni validación técnica.'] },
      { titulo: '6. Disponibilidad del sitio y cambios', parrafos: ['Podemos actualizar el catálogo, corregir errores y modificar estos términos. Los cambios se publicarán en esta página. Procuramos mantener el servicio disponible, pero puede haber interrupciones por mantenimiento o causas técnicas. Nada de lo aquí dispuesto elimina derechos de consumidores ni responsabilidades que legalmente no puedan excluirse.'] },
      { titulo: '7. Ley aplicable y reclamaciones', parrafos: ['Se aplica la legislación de la República de Colombia. Para consultas, peticiones, quejas o reclamos contacta al WhatsApp +57 316 329 3151 o visita Carrera 65 #28-27, barrio Trinidad, Medellín, Antioquia.'] },
    ],
  },
  'politica-cookies': {
    titulo: 'Política de Cookies y Tecnologías Similares',
    actualizado: '30 de septiembre de 2026',
    introduccion: 'Esta política identifica las tecnologías de almacenamiento usadas por el sitio y permite cambiar las preferencias desde el enlace “Preferencias de cookies” al pie de cada página.',
    secciones: [
      { titulo: '1. Qué usamos', parrafos: ['Necesarias: almacenamiento local de la elección de cookies; cookie de sesión segura admin_session para el acceso administrativo; y almacenamiento de sesión del navegador para recordar el punto de regreso en el catálogo. Se usan para seguridad, navegación y funcionamiento solicitado.', 'Tecnología funcional de modelos 3D: la biblioteca de Google Model Viewer se descarga desde Google al abrir una ficha con modelo 3D; para decodificar el formato comprimido se solicita también un pequeño componente técnico desde jsDelivr. El archivo del modelo se sirve desde este sitio. Estas solicitudes son necesarias para ofrecer el visor interactivo y no se usan aquí para medir visitas ni publicidad.', 'Analítica opcional: Vercel Analytics, que se activa solo si aceptas la categoría Analítica. Ayuda a entender el uso agregado del sitio y puede emplear identificadores o almacenamiento según su configuración vigente.', 'Herramientas externas opcionales: el chat Tidio solo se activa si aceptas Herramientas externas. El mapa de Google Maps no se carga hasta que pulsas “Cargar mapa” o “Abrir Google Maps”. WhatsApp, enlaces sociales y otros sitios externos solo reciben una solicitud cuando eliges abrir sus enlaces y se rigen por sus propias políticas.'] },
      { titulo: '2. Elección y retiro del consentimiento', parrafos: ['Al ingresar puedes aceptar todas las categorías, rechazar las opcionales o configurarlas por separado. Las opciones de Analítica y Herramientas externas vienen desmarcadas. No condicionamos la navegación del catálogo a aceptar opciones no necesarias.', 'Puedes cambiar o retirar tu elección en cualquier momento con el control al pie de página. El cambio impide nuevas cargas opcionales; para borrar datos que un proveedor ya haya almacenado, usa además los controles del navegador o contacta al proveedor correspondiente.'] },
      { titulo: '3. Control desde el navegador', parrafos: ['El navegador permite bloquear o eliminar cookies. Si se bloquean las necesarias, algunas funciones de seguridad o navegación pueden dejar de funcionar. Las instrucciones dependen del navegador y dispositivo que utilices.'] },
      { titulo: '4. Contacto y cambios', parrafos: ['Para preguntas sobre cookies o datos personales, contacta a ParteMaquinas por WhatsApp +57 316 329 3151 o en Carrera 65 #28-27, barrio Trinidad, Medellín, Antioquia. La razón social y el NIT del responsable deben ser completados por el titular antes de publicar definitivamente las políticas. Esta política puede actualizarse si cambia la tecnología del sitio; se mostrará la fecha vigente al inicio.'] },
    ],
  },
  'derecho-retracto': {
    titulo: 'Política de Derecho de Retracto',
    actualizado: '30 de septiembre de 2026',
    introduccion: 'Esta página explica cómo solicitar el retracto cuando sea aplicable a una compra a distancia realizada con ParteMaquinas. No limita los demás derechos de garantía, reversión de pagos o protección al consumidor.',
    secciones: [
      { titulo: '1. Plazo', parrafos: ['En los contratos de venta a distancia y demás supuestos contemplados en el artículo 47 de la Ley 1480 de 2011, puedes ejercer el retracto dentro de los cinco (5) días hábiles contados desde la entrega del bien. El retracto no es una política comercial discrecional: se tramitará cuando se cumplan las condiciones legales.'] },
      { titulo: '2. Cómo solicitarlo', parrafos: ['Envía tu solicitud escrita al WhatsApp +57 316 329 3151 o entrégala en Carrera 65 #28-27, barrio Trinidad, Medellín, Antioquia. Indica “Solicitud de retracto”, nombre, número de pedido o factura, fecha de entrega, producto y una forma de contacto. Conserva la constancia de envío. Te confirmaremos el trámite y la dirección o coordinación de devolución.', 'Devuelve el producto por los mismos medios y en las condiciones en que lo recibiste, teniendo en cuenta las reglas legales aplicables. Los costos de transporte y demás gastos de devolución corresponden al consumidor conforme al artículo 47 de la Ley 1480 de 2011.'] },
      { titulo: '3. Reembolso', parrafos: ['Al aceptar el retracto se resuelve la operación y se reintegran las sumas pagadas sin descuentos ni retenciones por el retracto. La devolución del dinero se realizará a más tardar dentro de treinta (30) días calendario contados desde el ejercicio del derecho, según la ley y el medio de pago utilizado. No se sustituye unilateralmente por bonos o saldo a favor.'] },
      { titulo: '4. Casos en que la ley excluye el retracto', parrafos: ['El retracto no procede en los casos previstos por el artículo 47 de la Ley 1480 de 2011, entre ellos: servicios cuya prestación haya comenzado con acuerdo del consumidor; productos confeccionados conforme a sus especificaciones o claramente personalizados; bienes que por su naturaleza no puedan devolverse o puedan deteriorarse o caducar rápidamente; bienes de uso personal; y los demás supuestos legales. La excepción se aplica según la naturaleza concreta del producto y la ley, no por una regla general que elimine derechos del consumidor.'] },
      { titulo: '5. Garantía y reversión del pago son mecanismos distintos', parrafos: ['Si el producto presenta una falla o no corresponde a lo ofrecido, puedes solicitar la efectividad de la garantía legal sin que venza por ello el plazo de retracto. La reversión de pagos electrónicos tiene causales y plazos propios (por ejemplo, fraude, operación no solicitada, producto no recibido, distinto o defectuoso) y requiere actuar también ante el emisor del instrumento de pago, conforme al artículo 51 de la Ley 1480 y su reglamentación.'] },
    ],
  },
};
